ChangeEveryLetterToTheNextLetter updated  !
Anishluke92/ProblemSolving pull request #21
Opened 2020-10-26 00:37 UTC by Anishluke92

2020-11-01 20:31 UTC, danielpaul requested changes

2020-11-01 20:31 UTC, danielpaul commented on ChangeEveryLetterToTheNextLetter.rb
> +    index = alphabet.index(letter)
when you are looking for index, this is going through the array and then looking for index everytime. can you try do this in better performance?

2020-11-01 21:35 UTC, Anishluke92 commented on ChangeEveryLetterToTheNextLetter.rb
> +    index = alphabet.index(letter)
i will look into it now

2020-11-02 15:07 UTC, Anishluke92 commented on ChangeEveryLetterToTheNextLetter.rb
> +    index = alphabet.index(letter)
I tried it, But i couldn't  improve the performance

2020-11-04 23:45 UTC, danielpaul requested changes

2020-11-04 23:45 UTC, danielpaul commented on ChangeEveryLetterToTheNextLetter.rb
> +  word = word.downcase.scan /\w/
what does scan do?

2020-11-04 23:45 UTC, danielpaul commented on ChangeEveryLetterToTheNextLetter.rb
> +  word = word.downcase.scan /\w/
lets assume for now that you will only be given one word without spaces and number. that's what the examples are

2020-11-04 23:45 UTC, danielpaul commented on ChangeEveryLetterToTheNextLetter.rb
> +    arr.push(alphabet.key(alphabet[element]+1))
why not use a string? so you just add letters at the end of the string instead of an array

2020-11-04 23:45 UTC, danielpaul commented on ChangeEveryLetterToTheNextLetter.rb
> +    alphabet[key] = value
hash is a good idea. you get O(1) look up. so great for performance. but why are you storing the index value in the hash? 

you code below gets the index of it and then finds the next element with that but it need to loop through the hash to find the key. You lose the benefit of using the hash. 

How about you have a hash that look like this? 

```
{
  'a': 'b',
  'b': 'c',
  'c': 'd',
   ...
}
```

So when you have the key, you know immediately what that should be translated into.

2020-11-06 20:01 UTC, danielpaul commented on ChangeEveryLetterToTheNextLetter.rb
> +  string = " "
```suggestion
  string = ""
```

2020-11-06 20:01 UTC, danielpaul approved these changes

2020-11-06 20:02 UTC, merged