REcursion length of a string updated!
Anishluke92/ProblemSolving pull request #24
Opened 2020-10-26 11:26 UTC by Anishluke92

2020-10-29 00:00 UTC, danielpaul requested changes

2020-10-29 00:00 UTC, danielpaul commented on RecursionLengthOfAString.rb
> +def length(string)
not recursive. the important thing here is to write a recursive method that would do this.

2020-10-31 21:18 UTC, danielpaul commented
@Anishluke92 there are two or 3 other questions in this PR also? have a look at the file changes

2020-10-31 21:21 UTC, danielpaul requested changes

2020-10-31 21:21 UTC, danielpaul commented on RecursionLengthOfAString.rb
> +end
```suggestion
def length(string)
  return 0 if string == '' 
  1 + length(string.chop)  
end
```

2020-11-16 20:22 UTC, danielpaul commented
This is ready but you have a merge conflict. So task: Learn about merge conflicts and learn how to resolve them. once you know how, you can resolve this merge conflict and this can be merged in then.

2020-11-16 20:27 UTC, Anishluke92 commented
> This is ready but you have a merge conflict. So task: Learn about merge conflicts and learn how to resolve them. once you know how, you can resolve this merge conflict and this can be merged in then.

2022-05-11 13:33 UTC, merged