RecursionGCD is being updated !
Anishluke92/ProblemSolving pull request #25
Opened 2020-10-26 14:29 UTC by Anishluke92

2020-10-29 00:00 UTC, danielpaul requested changes

2020-10-29 00:00 UTC, danielpaul commented on RecursionGCD.rb
> +def gcd(a, b)
remove the printing out comments and return the answer

2020-11-16 20:24 UTC, danielpaul commented
I think you are using Git wrongly... there are all sorts of files being checked into different branches. You are committing the same files in lots of different branches. Thats not how it is supposed to work. Each branch is a different version of the codebase.

2020-11-16 20:24 UTC, danielpaul commented
Thats also why you are having a lot of merge conflicts. Can you fix this PR so it only have the changes that it should?

2020-11-16 20:34 UTC, Anishluke92 commented
I dont how other files are getting merged into this files ! when i'm working on a branch and its file is open and further when i switch it to  another branch and work on it. when i commit on the current the pervious branch  file which is opened will also get commit to the current branch

2020-11-16 20:34 UTC, Anishluke92 commented
I think thats how merge conflict happens

2020-11-16 20:36 UTC, Anishluke92 commented
> Thats also why you are having a lot of merge conflicts. Can you fix this PR so it only have the changes that it should?

Can you give me an hint how to fix it and i head on from there

2020-12-01 00:56 UTC, Anishluke92 commented
I have fixed the merge conflict ! but i have few doubts

2021-01-21 22:55 UTC, danielpaul approved these changes

2021-01-21 22:56 UTC, merged